export const ALGO_TRADE_PREFIX = 'algo-trade'

export const STORAGE_KEY_STRATEGY_CONFIG = 'algo-trade:strategy-config'
export const STORAGE_KEY_BROKER_ACCOUNTS = 'algo-trade:broker-accounts'
export const STORAGE_KEY_NOTIFICATIONS = 'algo-trade:notifications'
export const STORAGE_KEY_TICK_LOG = 'algo-trade:tick-log'
export const STORAGE_KEY_ACTIVE_USER = 'algo-trade:active-user'
export const STORAGE_KEY_LIVE_TRADES_PAGE_MODE =
  'algo-trade:livetradespage-mode'
export const STORAGE_KEY_BOT_STATE = 'algo-trade:bot-state'
export const STORAGE_KEY_BOT_POSITION = 'algo-trade:bot-position'
export const STORAGE_KEY_BOT_POSITIONS = 'algo-trade:bot-positions'
export const STORAGE_KEY_BOT_TRADES_TODAY = 'algo-trade:bot-trades-today'
export const STORAGE_KEY_BOT_TRADES_PER_SYMBOL =
  'algo-trade:bot-trades-per-symbol'
export const STORAGE_KEY_BOT_TRADES_DATE = 'algo-trade:bot-trades-date'
export const STORAGE_KEY_VRD_CACHE = 'algo-trade:vrd-cache'
export const STORAGE_KEY_BOT_LOGS = 'algo-trade:bot-logs'
export const STORAGE_KEY_BOT_SNAPSHOT = 'algo-trade:bot-snapshot'
export const STORAGE_KEY_BOT_EXIT_TIMES = 'algo-trade:bot-last-exit-times'
export const STORAGE_KEY_PROXY_HISTORY = 'algo-trade:proxy-history'

export const REMOTE_STATE_KEY_STRATEGY_CONFIG = 'strategyConfig'
export const REMOTE_STATE_KEY_BROKER_ACCOUNTS = 'brokerAccounts'

export const API_PAPER_ACCOUNT = '/api/paper/account'
export const API_PAPER_HISTORY = '/api/paper/history'
export const API_PAPER_ACCOUNT_ADJUST = '/api/paper/account/adjust'
export const API_PAPER_RESET = '/api/paper/reset'
export const API_PAPER_TRADES_ENTER = '/api/paper/trades/enter'
export const API_PAPER_TRADES_EXIT = '/api/paper/trades/exit'
export const API_CLIENT_STATE = '/api/client-state'
export const API_UPSTOX_PROFILE = '/api/broker/upstox/profile'
export const API_UPSTOX_FUNDS = '/api/broker/upstox/funds'
export const API_UPSTOX_TOKEN = '/api/broker/upstox/token'
export const API_ORDER_LIST = '/api/order/list'
export const API_ORDER_PLACE = '/api/order/place'
export const API_MARKET_VIX = '/api/market/vix'
export const API_MARKET_FII = '/api/market/upstox/fii'
export const API_MARKET_DII = '/api/market/upstox/dii'
export const API_MARKET_NEWS = '/api/market/upstox/news'
export const API_MARKET_PCR = '/api/market/upstox/pcr'
export const API_MARKET_MAX_PAIN = '/api/market/upstox/max-pain'
export const API_MARKET_CANDLES_INTRADAY = '/api/market/candles/intraday'
export const API_MARKET_BREADTH = '/api/market/breadth'
export const API_MARKET_OPTION_CONTRACTS = '/api/market/option-contracts'
export const API_MARKET_GLOBAL_INDICES = '/api/market/upstox/global-indices'
export const API_MARKET_OPTION_CHAIN = '/api/market/option-chain'
export const API_MARKET_QUOTES = '/api/market/quotes'
export const API_MARKET_INDICES = '/api/market/indices'

export const MCP_UPSTOX_URL = 'https://mcp.upstox.com/mcp'
export const UPSTOX_MCP_DOCS_URL =
  'https://upstox.com/developer/api-documentation/mcp-integration'
export const UPSTOX_AUTH_URL =
  'https://api.upstox.com/v2/login/authorization/dialog'
export const UPSTOX_DEVELOPER_APPS_URL =
  'https://account.upstox.com/developer/apps#analytics'
export const UPSTOX_DEVELOPER_APPS_BASE_URL =
  'https://account.upstox.com/developer/apps'

export const SIGNAL_BUY_CE = 'BUY_CE'
export const SIGNAL_BUY_PE = 'BUY_PE'
export const SIGNAL_WAIT = 'WAIT'
export const SIGNAL_NO_TRADE = 'NO_TRADE'
export const TRADE_TYPE_SELLING = 'selling'
export const TRADE_TYPE_BUYING = 'buying'
export const TRADE_TYPE_BOTH = 'both'
export const SIGNAL_BUY = 'Buy'
export const SIGNAL_SELL = 'Sell'
export const SIGNAL_HOLD = 'Hold'
export const ORDER_TYPE_BUY = 'buy'
export const ORDER_TYPE_SELL = 'sell'
export const ORDER_TYPE_HOLD = 'hold'
export const CONFIDENCE_STRONG = 'strong'
export const CONFIDENCE_MODERATE = 'moderate'
export const CONFIDENCE_WEAK = 'weak'
export const CONFIDENCE_NONE = 'none'
export const POSITION_SIZE_FULL = 'full'
export const POSITION_SIZE_HALF = 'half'
export const POSITION_SIZE_NONE = 'none'
export const TRADE_STATUS_WIN = 'WIN'
export const TRADE_STATUS_LOSS = 'LOSS'
export const TRADE_STATUS_ACTIVE = 'ACTIVE'
export const TRADE_STATUS_CLOSED = 'CLOSED'
export const TRADE_STATUS_SL_HIT = 'SL_HIT'
export const TRADE_STATUS_TARGET_HIT = 'TARGET_HIT'
export const TRADE_STATUS_COMPLETED = 'COMPLETED'
export const TRADE_STATUS_CANCELLED = 'CANCELLED'
export const TRADE_STATUS_REJECTED = 'REJECTED'
export const LEG_DIRECTION_CE = 'CE'
export const LEG_DIRECTION_PE = 'PE'
export const MARKET_DATA_NSE_FO_INDEX_FUTURES = 'NSE_FO|INDEX_FUTURES'
export const MARKET_DATA_NSE_EQ_CASH = 'NSE_EQ|CASH'
export const MOMENTUM_OVERBOUGHT = 'Overbought'
export const MOMENTUM_OVERSOLD = 'Oversold'

export const MAX_LOGS = 200
export const VRD_CACHE_MAX_MS = 30 * 60 * 1000
export const COOLDOWN_MS = 60 * 1000
export const MAX_TICKS = 500
