service: algo-trade-cron

frameworkVersion: "3"

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs14.x
  stackName: algo-trade-cron-stack
  timeout: 30
  iam:
    role:
      name: algo-trade-cron-${sls:stage}
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - Fn::GetAtt: [ sentimentTable, Arn ]
            - Fn::GetAtt: [ sentimentLastTable, Arn ]
            - Fn::GetAtt: [ tradeLogDayTable, Arn ]
            - arn:aws:dynamodb:ap-south-1:715637905274:table/algo_trade_log
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - 'arn:aws:sns:*'

functions:
  cron:
    handler: dist/cron.run
    name: ${sls:stage}-algo-trade-cron
    events:
      - schedule:
          name: algo-trade-cron-9_29am
          description: Cron Job from 9-29 am (1 min)
          rate: cron(59/1 3 ? * MON-FRI *)
      - schedule:
          name: algo-trade-cron-9_30am-to-2_30pm
          description: Cron Job from 9-31 am to 2-29 pm (5 hours)
          rate: cron(0/1 4-8 ? * MON-FRI *)
      - schedule:
          name: algo-trade-cron-2_30pm-to-3_01pm
          description: Cron Job from 2-30 pm to 3-01 pm (31 mins)
          rate: cron(0-31/1 9 ? * MON-FRI *)
  reset:
    handler: dist/cron.reset
    name: ${sls:stage}-algo-trade-cron-reset-day-trades
    events:
      - schedule:
          name: algo-trade-cron-reset-day-trades
          description: Cron Job every day after end of market
          rate: cron(0 12 ? * MON-FRI *)
  dayTrades:
      handler: dist/cron.daysTradesLog
      name: ${sls:stage}-algo-trade-cron-update-day-trades
      events:
        - schedule:
            name: algo-trade-cron-update-day-trades
            description: Cron Job every day after end of market
            rate: cron(0 12 ? * MON-FRI *)

resources:
  Resources:
    sentimentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: algo_trade_sentiment
        KeySchema:
          - AttributeName: date_time
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: date_time
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    sentimentLastTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: algo_trade_sentiment_latest
        KeySchema:
          - AttributeName: latest
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: latest
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5  
    tradeLogDayTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: algo_trade_log_day
        KeySchema:
          - AttributeName: tradeDate
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: tradeDate
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5