service: algo-trade-cron

frameworkVersion: "3"

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs14.x
  stackName: algo-trade-cron-stack
  timeout: 30
  websocketsApiName: algo-trade-websockets
  websocketsApiRouteSelectionExpression: $request.body.action
  websocketsDescription: Algo Trading WebSocket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeStream
            - dynamodb:ListStreams
            - dynamodb:GetShardIterator
            - dynamodb:GetRecords
            - apigateway:*
          Resource:
            - Fn::GetAtt: [ sentimentTable, Arn ]
            - Fn::GetAtt: [ sentimentLastTable, Arn ]

functions:
  cron:
    handler: dist/cron.run
    name: ${sls:stage}-algo-trade-cron
    events:
      # Invoke Lambda function every minute from Mon-Fri 9:30-3:30
      - schedule: cron(0/1 4-10 ? * MON-FRI *)
  websocketHandler:
    handler: dist/websocket.run
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

resources:
  Resources:
    sentimentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: algo_trade_sentiment
        KeySchema:
          - AttributeName: date_time
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: date_time
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    sentimentLastTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: algo_trade_sentiment_latest
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        KeySchema:
          - AttributeName: latest
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: latest
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5  
