service: algo-trade-cron

frameworkVersion: "3"

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs14.x
  stackName: algo-trade-cron-stack
  timeout: 30
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ sentimentTable, Arn ]
            - Fn::GetAtt: [ sentimentLastTable, Arn ]

functions:
  cron:
    handler: dist/cron.run
    name: ${sls:stage}-algo-trade-cron
    events:
      - schedule:
          name: algo-trade-cron-9_29am
          description: Cron Job from 9-29 am (1 min)
          rate: cron(59/1 3 ? * MON-FRI *)
      - schedule:
          name: algo-trade-cron-9_30am-to-2_30pm
          description: Cron Job from 9-31 am to 2-29 pm (5 hours)
          rate: cron(0/1 4-8 ? * MON-FRI *)
      - schedule:
          name: algo-trade-cron-2_30pm-to-3_01pm
          description: Cron Job from 2-30 pm to 3-01 pm (31 mins)
          rate: cron(0-31/1 9 ? * MON-FRI *)

resources:
  Resources:
    sentimentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: algo_trade_sentiment
        KeySchema:
          - AttributeName: date_time
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: date_time
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    sentimentLastTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: algo_trade_sentiment_latest
        KeySchema:
          - AttributeName: latest
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: latest
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5  
